-- Generated by scripts/tts/build_audio_seed.mjs — do not edit by hand.
-- 18 AI (Kokoro-82M) + 18 real (LibriSpeech test-clean) voice clips.
-- Files live in the public 'challenges' bucket under audio/ai and audio/real.

begin;

-- Legacy placeholder rows may be referenced by question_attempts (FK) and cannot be
-- deleted, so deactivate them; sampling only returns is_active rows.
update public.questions set is_active = false
where category_id = 'audio' and metadata->>'seedId' like 'aud-%';

-- Remove previously seeded clips that have no attempts, so re-runs stay clean without
-- violating the question_attempts foreign key.
delete from public.questions q
where q.category_id = 'audio'
  and (q.metadata->>'seedId' like 'ai-%' or q.metadata->>'seedId' like 'real-%')
  and not exists (select 1 from public.question_attempts a where a.question_id = q.id);

insert into public.questions
  (category_id, media_url, is_ai, difficulty_rating, explanation_text, is_active, metadata)
values
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-01.wav', true, 'EASY', NULL, true, '{"kind":"audio","seedId":"ai-01","durationMs":6030,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-02.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-02","durationMs":5530,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-03.wav', true, 'HARD', NULL, true, '{"kind":"audio","seedId":"ai-03","durationMs":5130,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-04.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-04","durationMs":5910,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-05.wav', true, 'EASY', NULL, true, '{"kind":"audio","seedId":"ai-05","durationMs":6180,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-06.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-06","durationMs":5240,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-07.wav', true, 'HARD', NULL, true, '{"kind":"audio","seedId":"ai-07","durationMs":5960,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-08.wav', true, 'EASY', NULL, true, '{"kind":"audio","seedId":"ai-08","durationMs":5810,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-09.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-09","durationMs":5420,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-10.wav', true, 'HARD', NULL, true, '{"kind":"audio","seedId":"ai-10","durationMs":4940,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-11.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-11","durationMs":5720,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-12.wav', true, 'EASY', NULL, true, '{"kind":"audio","seedId":"ai-12","durationMs":5460,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-13.wav', true, 'HARD', NULL, true, '{"kind":"audio","seedId":"ai-13","durationMs":6240,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-14.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-14","durationMs":5750,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-15.wav', true, 'EASY', NULL, true, '{"kind":"audio","seedId":"ai-15","durationMs":6410,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-16.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-16","durationMs":5940,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-17.wav', true, 'HARD', NULL, true, '{"kind":"audio","seedId":"ai-17","durationMs":5240,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/ai/ai-18.wav', true, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"ai-18","durationMs":5630,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-01.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-01","durationMs":4910,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-02.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-02","durationMs":5960,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-03.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-03","durationMs":6560,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-04.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-04","durationMs":6390,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-05.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-05","durationMs":6420,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-06.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-06","durationMs":6280,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-07.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-07","durationMs":5880,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-08.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-08","durationMs":6090,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-09.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-09","durationMs":4830,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-10.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-10","durationMs":6040,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-11.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-11","durationMs":6020,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-12.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-12","durationMs":5440,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-13.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-13","durationMs":5990,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-14.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-14","durationMs":5330,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-15.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-15","durationMs":6240,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-16.wav', false, 'MEDIUM', NULL, true, '{"kind":"audio","seedId":"real-16","durationMs":6120,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-17.wav', false, 'HARD', NULL, true, '{"kind":"audio","seedId":"real-17","durationMs":6300,"mimeType":"audio/wav"}'::jsonb),
  ('audio', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/audio/real/real-18.wav', false, 'EASY', NULL, true, '{"kind":"audio","seedId":"real-18","durationMs":4960,"mimeType":"audio/wav"}'::jsonb);

commit;
