-- Bot Or Not — curated email dataset. GENERATED from data/emails.json by
-- scripts/build-email-seed.mjs. Do not edit by hand; edit the JSON and regenerate.
-- Idempotent (guarded by metadata->>'seedId'). 40 emails.

-- Retire the original placeholder emails (kept in table, just hidden from play).
UPDATE questions SET is_active = false
WHERE category_id = 'email' AND metadata->>'seedId' IN ('eml-001','eml-002','eml-003','eml-004','eml-005','eml-006');

INSERT INTO questions (category_id, media_url, is_ai, difficulty_rating, explanation_text, metadata)
SELECT 'email', v.body, v.is_ai, v.difficulty_rating, v.explanation, v.metadata
FROM (VALUES
  ('<p>Dear Customer,<br>We detect unusual activity in your account. You must to confirm your password immediately or your account will be permanently suspend. Kindly verify here: https://secure-verify-account.info/login</p>', true, 'EASY', 'Stacked red flags: generic ''Dear Customer'', broken grammar (''must to confirm'', ''will be suspend''), a threat to create urgency, an unrelated ''.info'' domain, and a request to confirm your password — which no legitimate service ever asks for.', '{"kind":"email","subject":"Account Will Be Suspend !!","senderName":"Security Team","senderAddress":"support@secure-verify-account.info","bodyFormat":"html","seedId":"eml-101"}'::jsonb),
  ('<p>Hello Dear,<br>Your package is hold at our facility because of unpaid customs fee of $2.99. Please to pay now otherwise parcel will be return: https://dhl-parcel-clearance.top/pay</p>', true, 'EASY', '''Hello Dear'', awkward grammar (''is wait'', ''Please to pay''), a tiny fee designed to bait a card entry, and a suspicious ''.top'' domain unrelated to dhl.com.', '{"kind":"email","subject":"Your parcel is wait for you","senderName":"DHL Notification","senderAddress":"auto@dhl-parcel-clearance.top","bodyFormat":"html","seedId":"eml-102"}'::jsonb),
  ('<p>Hey team, quick notes from this morning''s standup are in the shared doc. Nothing blocking this week. Thanks!</p>', false, 'EASY', 'Internal sender on company.com, natural tone, and no links or requests to act on — an ordinary colleague message.', '{"kind":"email","subject":"Standup notes — Tue","senderName":"Marcus Lee","senderAddress":"marcus.lee@company.com","bodyFormat":"html","seedId":"eml-103"}'::jsonb),
  ('<p>You have 3 new connection requests waiting. Sign in to LinkedIn to respond.</p>', false, 'EASY', 'Genuine linkedin.com domain, informational, and it does not ask for credentials.', '{"kind":"email","subject":"You have 3 new invitations","senderName":"LinkedIn","senderAddress":"notifications-noreply@linkedin.com","bodyFormat":"html","seedId":"eml-104"}'::jsonb),
  ('<p>New this month: variables, improved auto-layout, and more. Read the full changelog on figma.com.</p>', false, 'EASY', 'Legitimate figma.com sender; a routine product newsletter with nothing to act on.', '{"kind":"email","subject":"What''s new in Figma this month","senderName":"Figma","senderAddress":"updates@figma.com","bodyFormat":"html","seedId":"eml-105"}'::jsonb),
  ('<p>You sent a payment of $649.99 to Tech Store Ltd. If you did not authorize this, cancel within 24 hours: https://paypal-notifications.com/cancel</p>', true, 'MEDIUM', 'A fake ''you paid'' alarm to make you click in a panic. PayPal emails come from paypal.com; ''paypal-notifications.com'' is a look-alike domain.', '{"kind":"email","subject":"You sent a payment of $649.99","senderName":"PayPal Service","senderAddress":"service@paypal-notifications.com","bodyFormat":"html","seedId":"eml-106"}'::jsonb),
  ('<p>We has detected a sign-in from a new device. If this wasnt you, please verify you identity here: https://microsoft365-alerts.com/verify</p>', true, 'MEDIUM', 'Grammar slips (''We has detected'', ''wasnt'', ''you identity'') plus a look-alike domain; Microsoft uses microsoft.com, not ''microsoft365-alerts.com''.', '{"kind":"email","subject":"Unusual sign in activity","senderName":"Microsoft 365","senderAddress":"no-reply@microsoft365-alerts.com","bodyFormat":"html","seedId":"eml-107"}'::jsonb),
  ('<p>Your invoice for $420.00 is available. View or download it from your dashboard: https://dashboard.stripe.com/invoices</p>', false, 'MEDIUM', 'It''s an invoice, but everything is consistent: a stripe.com sender and a dashboard.stripe.com link. The topic alone doesn''t make it a scam.', '{"kind":"email","subject":"Invoice 4F2A-9C for $420.00","senderName":"Stripe","senderAddress":"invoice+statements@stripe.com","bodyFormat":"html","seedId":"eml-108"}'::jsonb),
  ('<p>A payment of $1,204.00 to your credit card posted today. You can review recent activity by signing in at chase.com.</p>', false, 'MEDIUM', 'An alarming amount, but the sender is chase.com and it only reports activity — no link to a login form and no request for details.', '{"kind":"email","subject":"A payment of $1,204.00 posted","senderName":"Chase","senderAddress":"no.reply.alerts@chase.com","bodyFormat":"html","seedId":"eml-109"}'::jsonb),
  ('<p>We noticed a new sign-in to your Microsoft account on a Windows PC. If this wasn''t you, secure your account here: https://rnicrosoft.com/security</p>', true, 'HARD', 'The copy is clean, so the domain is the tell: ''rnicrosoft.com'' uses the letters r and n to imitate an m. The real domain is microsoft.com.', '{"kind":"email","subject":"New sign-in to your account","senderName":"Microsoft account team","senderAddress":"account-security-noreply@rnicrosoft.com","bodyFormat":"html","seedId":"eml-110"}'::jsonb),
  ('<p>Your Apple ID was used to sign in to iCloud on a new device. If this wasn''t you, review activity: https://appleid-verify.com/signin</p>', true, 'HARD', 'Even though the sender name looks right, the action link goes to ''appleid-verify.com'', not apple.com — a link mismatch. Check the destination, not just the sender.', '{"kind":"email","subject":"Your Apple ID was used to sign in","senderName":"Apple","senderAddress":"no-reply@apple.com","bodyFormat":"html","seedId":"eml-111"}'::jsonb),
  ('<p>Security info was recently added to your Microsoft account. If this was you, no action is needed. You can manage security info at account.microsoft.com.</p>', false, 'HARD', 'The long subdomain ''accountprotection.microsoft.com'' looks intimidating but is a genuine Microsoft domain; the email informs and points to account.microsoft.com.', '{"kind":"email","subject":"Security info was added","senderName":"Microsoft account team","senderAddress":"account-security-noreply@accountprotection.microsoft.com","bodyFormat":"html","seedId":"eml-112"}'::jsonb),
  ('<p>Hi — following up on our call. Can you process the $8,400 payment to the new vendor today? I''ll send the remittance details separately. Thanks, Sarah</p>', true, 'EXPERT', 'Reads like a normal colleague, but the domain is ''cornpany.com'' (c-o-r-n mimicking the m in company.com) — an external sender impersonating an internal one (business email compromise).', '{"kind":"email","subject":"Re: Vendor payment","senderName":"Sarah Chen","senderAddress":"sarah.chen@cornpany.com","bodyFormat":"html","seedId":"eml-113"}'::jsonb),
  ('<p>John Alvarez sent you ''Mutual NDA'' to review and sign. You can open it in DocuSign to continue.</p>', false, 'EXPERT', 'docusign.net is DocuSign''s genuine sending domain (not docusign.com), which can look off but is legitimate; there''s no credential request.', '{"kind":"email","subject":"John Alvarez sent you a document to review","senderName":"DocuSign","senderAddress":"dse_na4@docusign.net","bodyFormat":"html","seedId":"eml-114"}'::jsonb),
  ('<p>Payroll is processing. Please confirm your direct deposit details before the cutoff: https://workday-hrportal.com/dd</p>', true, 'MEDIUM', 'Workday runs on myworkday.com; ''workday-hrportal.com'' is a look-alike built to capture your bank details.', '{"kind":"email","subject":"Action needed: confirm direct deposit","senderName":"Workday","senderAddress":"no-reply@workday-hrportal.com","bodyFormat":"html","seedId":"eml-115"}'::jsonb),
  ('<p>Reminder: please submit your timesheet by Friday 5pm in Workday. The link is on the intranet.</p>', false, 'MEDIUM', 'Internal payroll from company.com; a routine reminder with no external link or data request.', '{"kind":"email","subject":"Timesheet reminder","senderName":"HR — Payroll","senderAddress":"payroll@company.com","bodyFormat":"html","seedId":"eml-116"}'::jsonb),
  ('<p>Your refund of $63.20 is ready. To receive it, confirm the card on file: https://arnazon.com/refund</p>', true, 'HARD', '''arnazon.com'' uses r-n to imitate the m in amazon.com — and Amazon never asks you to re-confirm a card to receive a refund.', '{"kind":"email","subject":"Your refund is ready","senderName":"Amazon.com","senderAddress":"returns@arnazon.com","bodyFormat":"html","seedId":"eml-117"}'::jsonb),
  ('<p>We''ve issued your refund of $24.30 to your Visa ending in 4412. It may take 3-5 business days to appear.</p>', false, 'MEDIUM', 'An amazon.com sender that states an outcome, requests nothing, and doesn''t link to any form.', '{"kind":"email","subject":"Refund issued","senderName":"Amazon.com","senderAddress":"auto-confirm@amazon.com","bodyFormat":"html","seedId":"eml-118"}'::jsonb),
  ('<p>Dear user, to protect you account please reply with the 6 digit code we just send to your phone. Failure to do so will lock you account.</p>', true, 'EASY', 'No real bank asks you to share a one-time code. Combined with ''Dear user'', grammar errors, and an unrelated domain, it''s clearly phishing.', '{"kind":"email","subject":"Verify your one time code","senderName":"Bank Support","senderAddress":"helpdesk@online-bank-secure.com","bodyFormat":"html","seedId":"eml-119"}'::jsonb),
  ('<p>You have 5 unread messages in #project-orion. Open Slack to catch up.</p>', false, 'EASY', 'Genuine slack.com sender; a routine notification.', '{"kind":"email","subject":"You have unread messages","senderName":"Slack","senderAddress":"feedback@slack.com","bodyFormat":"html","seedId":"eml-120"}'::jsonb),
  ('<p>A document ''Contract_Final.pdf'' was shared with you. Open it here: https://google-docs-share.com/d/xY7</p>', true, 'MEDIUM', 'Real Google sharing comes from google.com / docs.google.com; ''google-docs-share.com'' is an unrelated look-alike.', '{"kind":"email","subject":"Contract_Final has been shared with you","senderName":"Google Docs","senderAddress":"no-reply@google-docs-share.com","bodyFormat":"html","seedId":"eml-121"}'::jsonb),
  ('<p>Sharing the Q3 deck ahead of tomorrow: https://company.sharepoint.com/:p:/r/sites/marketing/Q3.pptx</p>', false, 'HARD', 'An internal company.com sender and a company.sharepoint.com link — both consistent with the organization, so it''s legitimate despite the long URL.', '{"kind":"email","subject":"Q3 deck","senderName":"Priya Nair","senderAddress":"priya.nair@company.com","bodyFormat":"html","seedId":"eml-122"}'::jsonb),
  ('<p>We''re having trouble with your current payment method. To avoid interruption, update your details: https://netfl1x.com/account</p>', true, 'EXPERT', '''netfl1x.com'' replaces the i with a 1; the genuine domain is netflix.com. The message itself is well written, so the domain is the only tell.', '{"kind":"email","subject":"We couldn''t process your payment","senderName":"Netflix","senderAddress":"info@netfl1x.com","bodyFormat":"html","seedId":"eml-123"}'::jsonb),
  ('<p>Your payment of $15.49 was received. You can manage your plan any time in Account settings.</p>', false, 'MEDIUM', 'account.netflix.com is a genuine Netflix domain; a simple receipt with nothing to click urgently.', '{"kind":"email","subject":"Your receipt from Netflix","senderName":"Netflix","senderAddress":"info@account.netflix.com","bodyFormat":"html","seedId":"eml-124"}'::jsonb),
  ('<p>Your mailbox has exceeded its storage limit. Re-validate your account to keep receiving mail: https://mailbox-revalidate.com</p>', true, 'MEDIUM', 'A corporate IT desk would not email from a personal gmail.com address, and the re-validation link points to an unrelated domain.', '{"kind":"email","subject":"Mailbox storage exceeded","senderName":"IT Helpdesk","senderAddress":"corp.it.helpdesk@gmail.com","bodyFormat":"html","seedId":"eml-125"}'::jsonb),
  ('<p>Heads up: VPN maintenance Saturday 10pm-2am. No action needed; access may be briefly unavailable.</p>', false, 'EASY', 'Internal company.com sender; informational, with nothing to click.', '{"kind":"email","subject":"Planned maintenance this weekend","senderName":"IT Service Desk","senderAddress":"servicedesk@company.com","bodyFormat":"html","seedId":"eml-126"}'::jsonb),
  ('<p>We attempted to deliver your package but no one was available. Reschedule your delivery: https://fedex-deliverysupport.com/reschedule</p>', true, 'HARD', 'The wording is clean, so the domain is the tell: FedEx uses fedex.com, and the added ''-deliverysupport'' marks a look-alike.', '{"kind":"email","subject":"Delivery attempt failed","senderName":"FedEx","senderAddress":"tracking@fedex-deliverysupport.com","bodyFormat":"html","seedId":"eml-127"}'::jsonb),
  ('<p>Your package is out for delivery and should arrive today. Track it at fedex.com/track.</p>', false, 'EASY', 'Sender and link are both fedex.com; a routine delivery update.', '{"kind":"email","subject":"Your package is out for delivery","senderName":"FedEx","senderAddress":"trackingupdates@fedex.com","bodyFormat":"html","seedId":"eml-128"}'::jsonb),
  ('<p>You have a document waiting for your signature. Review and sign it here: https://docusign-secure-sign.com/sign</p>', true, 'MEDIUM', 'DocuSign sends from docusign.net; ''docusign-secure-sign.com'' is an unrelated look-alike domain.', '{"kind":"email","subject":"You have a document waiting","senderName":"DocuSign","senderAddress":"dse@docusign-secure-sign.com","bodyFormat":"html","seedId":"eml-129"}'::jsonb),
  ('<p>Your Google Account was just signed in to on a new Windows device. If this was you, you don''t need to do anything. You can review activity in your account.</p>', false, 'MEDIUM', 'accounts.google.com is genuine; the alert is informational and does not ask for your password.', '{"kind":"email","subject":"Security alert: new sign-in on Windows","senderName":"Google","senderAddress":"no-reply@accounts.google.com","bodyFormat":"html","seedId":"eml-130"}'::jsonb),
  ('<p>You have been invited to ''Q2 Budget Review'' on Thursday 2:00pm. Join the meeting: https://g00gle-invites.com/j/BR2Q</p>', true, 'EXPERT', 'The invite looks completely routine, but ''g00gle'' uses zeros for the o''s; genuine invites come from google.com.', '{"kind":"email","subject":"Invitation: Q2 Budget Review","senderName":"Google Calendar","senderAddress":"calendar-invite@g00gle-invites.com","bodyFormat":"html","seedId":"eml-131"}'::jsonb),
  ('<p>You''ve been invited to ''Design sync'' on Monday 11:00am. The meeting link is meet.google.com/abc-defg.</p>', false, 'EASY', 'Genuine google.com sender and a meet.google.com link; an ordinary calendar invite.', '{"kind":"email","subject":"Invitation: Design sync","senderName":"Google Calendar","senderAddress":"calendar-notification@google.com","bodyFormat":"html","seedId":"eml-132"}'::jsonb),
  ('<p>Invoice INV-88213 for $1,290.00 is overdue. Please pay promptly to avoid a late fee: https://intuit-invoices.net/pay</p>', true, 'HARD', 'The invoice framing is normal — the domain is the tell. Intuit/QuickBooks invoices come from intuit.com; ''intuit-invoices.net'' is an unrelated look-alike.', '{"kind":"email","subject":"Invoice INV-88213 is overdue","senderName":"QuickBooks","senderAddress":"billing@intuit-invoices.net","bodyFormat":"html","seedId":"eml-133"}'::jsonb),
  ('<p>Your Apple ID was used to buy ''Logic Pro'' for $199.99. If you didn''t make this purchase, you can review your purchase history in the App Store.</p>', false, 'HARD', 'email.apple.com is genuine; the charge is alarming but the email only points you to the App Store, not to a login form.', '{"kind":"email","subject":"Your receipt from Apple","senderName":"Apple","senderAddress":"no_reply@email.apple.com","bodyFormat":"html","seedId":"eml-134"}'::jsonb),
  ('<p>All employee must to re-enroll in benefits before end of day today or coverage will be lost. Login here to confirm: https://company-benefits-portal.com</p>', true, 'MEDIUM', 'Grammar errors (''Update you benefits'', ''All employee must to re-enroll''), false urgency, and an external domain posing as your employer''s benefits portal.', '{"kind":"email","subject":"Update you benefits before deadline","senderName":"HR Department","senderAddress":"hr@company-benefits-portal.com","bodyFormat":"html","seedId":"eml-135"}'::jsonb),
  ('<p>Open enrollment runs Nov 4-15. No action needed today; details and the enrollment link will be posted on the intranet.</p>', false, 'MEDIUM', 'Internal company.com sender, no urgency, and no external link — a normal HR announcement.', '{"kind":"email","subject":"Open enrollment starts Monday","senderName":"People Team","senderAddress":"people@company.com","bodyFormat":"html","seedId":"eml-136"}'::jsonb),
  ('<p>We has place a hold on you account. To remove the hold you must confirm your card number and PIN here: https://secure-bank-online.com/unlock</p>', true, 'EASY', 'Banks never ask for your PIN by email. Combined with ''You account'', ''We has place'', and a generic domain, it''s clearly a scam.', '{"kind":"email","subject":"You account is on hold","senderName":"SecureBank Alert","senderAddress":"alert@secure-bank-online.com","bodyFormat":"html","seedId":"eml-137"}'::jsonb),
  ('<p>Your order of ''USB-C cable'' has shipped and arrives Thursday. You can track it in Your Orders.</p>', false, 'EASY', 'amazon.com sender; a routine shipping confirmation with no action needed.', '{"kind":"email","subject":"Your order has shipped","senderName":"Amazon.com","senderAddress":"ship-confirm@amazon.com","bodyFormat":"html","seedId":"eml-138"}'::jsonb),
  ('<p>Someone shared ''Payroll_2024.xlsx'' with you on Dropbox. View the file here: https://dropbox-fileshare.com/view</p>', true, 'HARD', 'The wording is clean, so check the domain: Dropbox shares come from dropbox.com, and ''dropbox-fileshare.com'' is a look-alike.', '{"kind":"email","subject":"A file was shared with you","senderName":"Dropbox","senderAddress":"no-reply@dropbox-fileshare.com","bodyFormat":"html","seedId":"eml-139"}'::jsonb),
  ('<p>The file you requested is ready to download from your Dropbox account. Sign in at dropbox.com to access it.</p>', false, 'MEDIUM', 'Genuine dropbox.com sender; informational.', '{"kind":"email","subject":"Your file is ready","senderName":"Dropbox","senderAddress":"no-reply@dropbox.com","bodyFormat":"html","seedId":"eml-140"}'::jsonb)
) AS v(body, is_ai, difficulty_rating, explanation, metadata)
WHERE NOT EXISTS (
  SELECT 1 FROM questions q WHERE q.metadata->>'seedId' = v.metadata->>'seedId'
);
