-- Generated by scripts/img/build_image_seed.mjs — do not edit by hand.
-- 25 image challenges from the 'data' branch (ai*/real*.jpg).
-- Files live in the public 'challenges' bucket under image/ai and image/real.

begin;

-- Legacy Picsum placeholders may be referenced by question_attempts (FK) and cannot be
-- deleted, so deactivate them; sampling only returns is_active rows.
update public.questions set is_active = false
where category_id = 'image' and metadata->>'seedId' like 'img-%';

-- Remove previously seeded image rows with no attempts so re-runs stay clean without
-- violating the question_attempts foreign key.
delete from public.questions q
where q.category_id = 'image'
  and (q.metadata->>'seedId' like 'ai%' or q.metadata->>'seedId' like 'real%')
  and not exists (select 1 from public.question_attempts a where a.question_id = q.id);

insert into public.questions
  (category_id, media_url, is_ai, difficulty_rating, explanation_text, is_active, metadata)
values
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai1.jpg', true, 'EASY', NULL, true, '{"kind":"image","seedId":"ai1","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai2.jpg', true, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"ai2","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai3.jpg', true, 'HARD', NULL, true, '{"kind":"image","seedId":"ai3","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai4.jpg', true, 'EASY', NULL, true, '{"kind":"image","seedId":"ai4","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai5.jpg', true, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"ai5","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai6.jpg', true, 'HARD', NULL, true, '{"kind":"image","seedId":"ai6","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai7.jpg', true, 'EASY', NULL, true, '{"kind":"image","seedId":"ai7","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai8.jpg', true, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"ai8","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai9.jpg', true, 'HARD', NULL, true, '{"kind":"image","seedId":"ai9","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai10.jpg', true, 'EASY', NULL, true, '{"kind":"image","seedId":"ai10","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai11.jpg', true, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"ai11","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai12.jpg', true, 'HARD', NULL, true, '{"kind":"image","seedId":"ai12","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/ai/ai13.jpg', true, 'EASY', NULL, true, '{"kind":"image","seedId":"ai13","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real1.jpg', false, 'EASY', NULL, true, '{"kind":"image","seedId":"real1","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real2.jpg', false, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"real2","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real3.jpg', false, 'HARD', NULL, true, '{"kind":"image","seedId":"real3","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real4.jpg', false, 'EASY', NULL, true, '{"kind":"image","seedId":"real4","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real5.jpg', false, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"real5","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real6.jpg', false, 'HARD', NULL, true, '{"kind":"image","seedId":"real6","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real7.jpg', false, 'EASY', NULL, true, '{"kind":"image","seedId":"real7","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real8.jpg', false, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"real8","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real9.jpg', false, 'HARD', NULL, true, '{"kind":"image","seedId":"real9","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real10.jpg', false, 'EASY', NULL, true, '{"kind":"image","seedId":"real10","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real11.jpg', false, 'MEDIUM', NULL, true, '{"kind":"image","seedId":"real11","source":"data-branch"}'::jsonb),
  ('image', 'https://urefnjrkmnnuhzmtjzte.supabase.co/storage/v1/object/public/challenges/image/real/real12.jpg', false, 'HARD', NULL, true, '{"kind":"image","seedId":"real12","source":"data-branch"}'::jsonb);

commit;
