-- Bot Or Not — development question seed.
-- Mirrors src/lib/dummyQuestions.ts.
-- Removes previous development seed rows before inserting current data.

DELETE FROM questions
WHERE metadata->>'seedId' IS NOT NULL;

INSERT INTO questions (
  category_id,
  media_url,
  is_ai,
  difficulty_rating,
  explanation_text,
  metadata
)
SELECT
  category_id,
  media_url,
  is_ai,
  difficulty_rating,
  explanation_text,
  metadata::jsonb
FROM (
  VALUES

  -- Images -----------------------------------------------------------------

  (
    'image',
    '/dataset/images/Real/real.jpg',
    false,
    'MEDIUM',
    'This image is labeled as a real photograph by the source dataset.',
    '{"kind":"image","altText":"Real photograph","seedId":"img-001"}'
  ),

  (
    'image',
    '/dataset/images/Ai/ai.jpg',
    true,
    'EASY',
    'This image is labeled AI-generated by the source dataset.',
    '{"kind":"image","altText":"AI-generated image","seedId":"img-002"}'
  ),

  (
    'image',
    '/dataset/images/Real/real1.jpg',
    false,
    'HARD',
    'This image is labeled as a real photograph by the source dataset.',
    '{"kind":"image","altText":"Real photograph","seedId":"img-003"}'
  ),

  (
    'image',
    '/dataset/images/Real/real2.jpg',
    false,
    'MEDIUM',
    'This image is labeled as a real photograph by the source dataset.',
    '{"kind":"image","altText":"Real photograph","seedId":"img-004"}'
  ),

  (
    'image',
    '/dataset/images/Ai/ai1.jpg',
    true,
    'EXPERT',
    'This image is labeled AI-generated by the source dataset.',
    '{"kind":"image","altText":"AI-generated image","seedId":"img-005"}'
  ),

  (
    'image',
    '/dataset/images/Ai/ai3.jpg',
    true,
    'EASY',
    'This image is labeled AI-generated by the source dataset.',
    '{"kind":"image","altText":"AI-generated image","seedId":"img-006"}'
  ),

  -- Emails -----------------------------------------------------------------

  (
    'email',
    '<p>Hello,</p><p>We noticed an unusual sign-in attempt on your PayPal account from a new device.</p><p>As a precaution, some account features have been temporarily restricted. Please review the activity and confirm that it was you.</p><p><a href="https://paypal-account-review.example/secure">Review recent activity</a></p><p>If you do not confirm your account within 24 hours, your ability to send and receive payments may remain limited.</p><p>Thank you,<br>PayPal Account Security</p>',
    true,
    'HARD',
    'This is a phishing email. The sender address and linked website do not use the official paypal.com domain. The message also pressures the recipient to act within 24 hours.',
    '{"kind":"email","subject":"Please review recent activity on your account","senderName":"PayPal Account Security","senderAddress":"security@paypal-account-review.example","bodyFormat":"html","seedId":"eml-001"}'
  ),

  (
    'email',
    '<p>Hi Jordan, attaching the Q3 report we discussed. Let me know if you want changes before Friday. Thanks!</p>',
    false,
    'EASY',
    'Known sender, no urgency, and no suspicious links; this is a legitimate message.',
    '{"kind":"email","subject":"Q3 report draft","senderName":"Alex Rivera","senderAddress":"alex.rivera@company.com","bodyFormat":"html","seedId":"eml-002"}'
  ),

  (
    'email',
    '<p>Hi Jordan,</p><p>Your Microsoft 365 password is scheduled to expire today. To avoid interruptions to Outlook and Teams, confirm your current sign-in before the end of the day.</p><p><a href="https://microsoft-security-check.example/session">Confirm account access</a></p><p>If you recently updated your password, no further action is required.</p><p>Microsoft 365 Support</p>',
    true,
    'HARD',
    'This is phishing. The sender and link do not use an official microsoft.com domain, and the deadline creates urgency.',
    '{"kind":"email","subject":"Action required: Password expiration notice","senderName":"Microsoft 365 Support","senderAddress":"account-notice@microsoft365-security.example","bodyFormat":"html","seedId":"eml-003"}'
  ),

  (
    'email',
    '<p>URGENT: I need you to purchase five $100 gift cards for a client and send the codes ASAP. I am in a meeting and cannot call. — Sent from my iPhone</p>',
    true,
    'HARD',
    'Classic CEO fraud: urgency, gift cards, and the claim that the sender cannot call.',
    '{"kind":"email","subject":"Quick favor","senderName":"CEO","senderAddress":"ceo.office@company-secure-mail.example","bodyFormat":"html","seedId":"eml-006"}'
  ),

  (
    'email',
    '<p>Hi Ethan,</p><p>This is a reminder that your appointment with Dr. Patel is scheduled for Monday, July 27 at 2:30 PM.</p><p>Please arrive 15 minutes early and bring your insurance card and photo ID.</p><p>To reschedule, call the number listed on the clinic website.</p><p>Best,<br>Bayview Medical Group</p>',
    false,
    'HARD',
    'This is legitimate. It provides appointment details without asking for credentials, payment, or a link click.',
    '{"kind":"email","subject":"Appointment reminder for July 27","senderName":"Bayview Medical Group","senderAddress":"appointments@bayviewmedical.org","bodyFormat":"html","seedId":"eml-007"}'
  ),

  (
    'email',
    '<p>Hi team,</p><p>I moved tomorrow''s design review from 10:00 AM to 10:30 AM so that Priya can attend.</p><p>The meeting location and video link in the calendar invitation have not changed.</p><p>Please add comments to the existing design document before the meeting.</p><p>Thanks,<br>Marcus</p>',
    false,
    'HARD',
    'This is legitimate. It refers to an existing meeting and document without adding a suspicious link or payment request.',
    '{"kind":"email","subject":"Design review moved to 10:30 AM","senderName":"Marcus Lee","senderAddress":"marcus.lee@northwindlabs.com","bodyFormat":"html","seedId":"eml-008"}'
  )

) AS v(
  category_id,
  media_url,
  is_ai,
  difficulty_rating,
  explanation_text,
  metadata
);
