// Generates supabase/seed_images.sql from the image challenge files in output/{ai,real}.
// media_url = full public URL into the `challenges` bucket (app consumes it verbatim).
// Idempotent: deactivates legacy Picsum placeholders (img-%) and clears prior childless
// image rows (ai%/real%) before inserting fresh.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');

const env = readFileSync(join(root, '.env.local'), 'utf8');
const url = env.match(/^NEXT_PUBLIC_SUPABASE_URL=(.*)$/m)[1].trim();
const publicBase = `${url}/storage/v1/object/public/challenges`;

const DIFF = ['EASY', 'MEDIUM', 'HARD'];
const sq = (s) => `'${String(s).replace(/'/g, "''")}'`;
const numOf = (name) => parseInt(name.replace(/\D/g, ''), 10) || 0;

function rows(sub, isAi) {
  const dir = join(here, 'output', sub);
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.jpg'))
    .sort((a, b) => numOf(a) - numOf(b));
  return files.map((file, i) => {
    const seedId = file.replace(/\.jpg$/, '');
    const mediaUrl = `${publicBase}/image/${sub}/${file}`;
    const metadata = { kind: 'image', seedId, source: 'data-branch' };
    return `  (${sq('image')}, ${sq(mediaUrl)}, ${isAi}, ${sq(DIFF[i % DIFF.length])}, NULL, true, ${sq(
      JSON.stringify(metadata),
    )}::jsonb)`;
  });
}

const values = [...rows('ai', true), ...rows('real', false)];

const sql = `-- Generated by scripts/img/build_image_seed.mjs — do not edit by hand.
-- ${values.length} image challenges from the 'data' branch (ai*/real*.jpg).
-- Files live in the public 'challenges' bucket under image/ai and image/real.

begin;

-- Legacy Picsum placeholders may be referenced by question_attempts (FK) and cannot be
-- deleted, so deactivate them; sampling only returns is_active rows.
update public.questions set is_active = false
where category_id = 'image' and metadata->>'seedId' like 'img-%';

-- Remove previously seeded image rows with no attempts so re-runs stay clean without
-- violating the question_attempts foreign key.
delete from public.questions q
where q.category_id = 'image'
  and (q.metadata->>'seedId' like 'ai%' or q.metadata->>'seedId' like 'real%')
  and not exists (select 1 from public.question_attempts a where a.question_id = q.id);

insert into public.questions
  (category_id, media_url, is_ai, difficulty_rating, explanation_text, is_active, metadata)
values
${values.join(',\n')};

commit;
`;

const out = join(root, 'supabase', 'seed_images.sql');
writeFileSync(out, sql);
console.log(`Wrote ${values.length} rows -> ${out}`);
