// Generates supabase/seed_audio.sql from the AI + real audio manifests.
// media_url = full public URL into the `challenges` bucket (app consumes it verbatim).
// Idempotent: clears prior seeded audio rows (by metadata.seedId) then inserts fresh.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');

const env = readFileSync(join(root, '.env.local'), 'utf8');
const url = env.match(/^NEXT_PUBLIC_SUPABASE_URL=(.*)$/m)[1].trim();
const publicBase = `${url}/storage/v1/object/public/challenges`;

const DIFF = { 1: 'EASY', 2: 'MEDIUM', 3: 'HARD' };
const sq = (s) => `'${String(s).replace(/'/g, "''")}'`;

function rows(manifest, sub) {
  return JSON.parse(readFileSync(join(here, 'output', sub, 'manifest.json'), 'utf8')).map((c) => {
    const mediaUrl = `${publicBase}/audio/${sub}/${c.file}`;
    const metadata = {
      kind: 'audio',
      seedId: c.id,
      durationMs: Math.round(c.duration_s * 1000),
      mimeType: 'audio/wav',
    };
    return `  (${sq('audio')}, ${sq(mediaUrl)}, ${c.is_ai}, ${sq(DIFF[c.difficulty])}, NULL, true, ${sq(
      JSON.stringify(metadata),
    )}::jsonb)`;
  });
}

const values = [...rows(null, 'ai'), ...rows(null, 'real')];

const sql = `-- Generated by scripts/tts/build_audio_seed.mjs — do not edit by hand.
-- 18 AI (Kokoro-82M) + 18 real (LibriSpeech test-clean) voice clips.
-- Files live in the public 'challenges' bucket under audio/ai and audio/real.

begin;

-- Legacy placeholder rows may be referenced by question_attempts (FK) and cannot be
-- deleted, so deactivate them; sampling only returns is_active rows.
update public.questions set is_active = false
where category_id = 'audio' and metadata->>'seedId' like 'aud-%';

-- Remove previously seeded clips that have no attempts, so re-runs stay clean without
-- violating the question_attempts foreign key.
delete from public.questions q
where q.category_id = 'audio'
  and (q.metadata->>'seedId' like 'ai-%' or q.metadata->>'seedId' like 'real-%')
  and not exists (select 1 from public.question_attempts a where a.question_id = q.id);

insert into public.questions
  (category_id, media_url, is_ai, difficulty_rating, explanation_text, is_active, metadata)
values
${values.join(',\n')};

commit;
`;

const out = join(root, 'supabase', 'seed_audio.sql');
writeFileSync(out, sql);
console.log(`Wrote ${values.length} rows -> ${out}`);
